// Code generated by protoc-gen-go.
// source: workflow.proto
// DO NOT EDIT!

/*
Package workFlowClient is a generated protocol buffer package.

It is generated from these files:
	workflow.proto

It has these top-level messages:
	Product
	PriceUpdateRequest
	PriceUpdateResponse
*/
package workFlowClient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	ProductId   int32   `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	ProductName string  `protobuf:"bytes,2,opt,name=product_name,json=productName" json:"product_name,omitempty"`
	Cost        float32 `protobuf:"fixed32,3,opt,name=cost" json:"cost,omitempty"`
	Status      string  `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Product) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *Product) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *Product) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Product) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type PriceUpdateRequest struct {
	Products []*Product `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
}

func (m *PriceUpdateRequest) Reset()                    { *m = PriceUpdateRequest{} }
func (m *PriceUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*PriceUpdateRequest) ProtoMessage()               {}
func (*PriceUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PriceUpdateRequest) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type PriceUpdateResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *PriceUpdateResponse) Reset()                    { *m = PriceUpdateResponse{} }
func (m *PriceUpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*PriceUpdateResponse) ProtoMessage()               {}
func (*PriceUpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PriceUpdateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "workFlowClient.Product")
	proto.RegisterType((*PriceUpdateRequest)(nil), "workFlowClient.PriceUpdateRequest")
	proto.RegisterType((*PriceUpdateResponse)(nil), "workFlowClient.PriceUpdateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WorkFlow service

type WorkFlowClient interface {
	SaveUpdatePriceForApproval(ctx context.Context, in *PriceUpdateRequest, opts ...grpc.CallOption) (*PriceUpdateResponse, error)
}

type workFlowClient struct {
	cc *grpc.ClientConn
}

func NewWorkFlowClient(cc *grpc.ClientConn) WorkFlowClient {
	return &workFlowClient{cc}
}

func (c *workFlowClient) SaveUpdatePriceForApproval(ctx context.Context, in *PriceUpdateRequest, opts ...grpc.CallOption) (*PriceUpdateResponse, error) {
	out := new(PriceUpdateResponse)
	err := grpc.Invoke(ctx, "/workFlowClient.WorkFlow/SaveUpdatePriceForApproval", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WorkFlow service

type WorkFlowServer interface {
	SaveUpdatePriceForApproval(context.Context, *PriceUpdateRequest) (*PriceUpdateResponse, error)
}

func RegisterWorkFlowServer(s *grpc.Server, srv WorkFlowServer) {
	s.RegisterService(&_WorkFlow_serviceDesc, srv)
}

func _WorkFlow_SaveUpdatePriceForApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkFlowServer).SaveUpdatePriceForApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workFlowClient.WorkFlow/SaveUpdatePriceForApproval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkFlowServer).SaveUpdatePriceForApproval(ctx, req.(*PriceUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkFlow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "workFlowClient.WorkFlow",
	HandlerType: (*WorkFlowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveUpdatePriceForApproval",
			Handler:    _WorkFlow_SaveUpdatePriceForApproval_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow.proto",
}

func init() { proto.RegisterFile("workflow.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0xc7, 0xed, 0x36, 0xb7, 0xf5, 0x26, 0x3e, 0x9c, 0xa0, 0x61, 0x20, 0xd4, 0xfa, 0xd2, 0xa7,
	0x0a, 0xdb, 0x27, 0x10, 0x61, 0xb0, 0x17, 0x19, 0x11, 0xf1, 0x51, 0x62, 0x1b, 0x47, 0xb1, 0xed,
	0xc5, 0x5c, 0xba, 0x7e, 0x7d, 0x21, 0xcb, 0x84, 0x29, 0xec, 0xed, 0xfe, 0x97, 0xbb, 0x5f, 0x7e,
	0x21, 0x70, 0xd9, 0x93, 0xfd, 0xfa, 0xac, 0xa9, 0xcf, 0x8d, 0x25, 0x47, 0xe8, 0xf3, 0xaa, 0xa6,
	0xfe, 0xa9, 0xae, 0x74, 0xeb, 0xd2, 0x1e, 0x26, 0x1b, 0x4b, 0x65, 0x57, 0x38, 0xbc, 0x05, 0x30,
	0xfb, 0xf2, 0xbd, 0x2a, 0x45, 0x94, 0x44, 0xd9, 0xb9, 0x8c, 0x43, 0x67, 0x5d, 0xe2, 0x1d, 0x5c,
	0x1c, 0x8e, 0x5b, 0xd5, 0x68, 0x31, 0x48, 0xa2, 0x2c, 0x96, 0xb3, 0xd0, 0x7b, 0x56, 0x8d, 0x46,
	0x84, 0x51, 0x41, 0xec, 0xc4, 0x30, 0x89, 0xb2, 0x81, 0xf4, 0x35, 0x5e, 0xc3, 0x98, 0x9d, 0x72,
	0x1d, 0x8b, 0x91, 0x5f, 0x08, 0x29, 0x5d, 0x03, 0x6e, 0x6c, 0x55, 0xe8, 0x57, 0x53, 0x2a, 0xa7,
	0xa5, 0xfe, 0xee, 0x34, 0x3b, 0x5c, 0xc2, 0x34, 0x00, 0x59, 0x44, 0xc9, 0x30, 0x9b, 0x2d, 0x6e,
	0xf2, 0x63, 0xe3, 0x3c, 0xe8, 0xca, 0xdf, 0xc1, 0xf4, 0x01, 0xae, 0x8e, 0x50, 0x6c, 0xa8, 0x65,
	0x8d, 0x02, 0x26, 0x8d, 0x66, 0x56, 0x5b, 0xed, 0x1f, 0x13, 0xcb, 0x43, 0x5c, 0x30, 0x4c, 0xdf,
	0x02, 0x14, 0xb7, 0x30, 0x7f, 0x51, 0xbb, 0xb0, 0xeb, 0x31, 0x2b, 0xb2, 0x8f, 0xc6, 0x58, 0xda,
	0xa9, 0x1a, 0xd3, 0xff, 0xb7, 0xff, 0x75, 0x9e, 0xdf, 0x9f, 0x9c, 0xd9, 0xcb, 0xa4, 0x67, 0x1f,
	0x63, 0xff, 0x01, 0xcb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xbe, 0xf8, 0xc8, 0x92, 0x01,
	0x00, 0x00,
}
