// Code generated by protoc-gen-go.
// source: workflow.proto
// DO NOT EDIT!

/*
Package workFlowClient is a generated protocol buffer package.

It is generated from these files:
	workflow.proto

It has these top-level messages:
	Entry
	Records
	Response
	Request
*/
package workFlowClient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	ProductId int32  `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *Entry) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Records struct {
	Entries []*Entry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *Records) Reset()                    { *m = Records{} }
func (m *Records) String() string            { return proto.CompactTextString(m) }
func (*Records) ProtoMessage()               {}
func (*Records) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Records) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Response struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*Entry)(nil), "workFlowClient.Entry")
	proto.RegisterType((*Records)(nil), "workFlowClient.Records")
	proto.RegisterType((*Response)(nil), "workFlowClient.Response")
	proto.RegisterType((*Request)(nil), "workFlowClient.Request")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WorkFlow service

type WorkFlowClient interface {
	PendingRecords(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Records, error)
	NotifyRecordsPicked(ctx context.Context, in *Records, opts ...grpc.CallOption) (*Response, error)
	NotifyRecordsProcessed(ctx context.Context, in *Records, opts ...grpc.CallOption) (*Response, error)
}

type workFlowClient struct {
	cc *grpc.ClientConn
}

func NewWorkFlowClient(cc *grpc.ClientConn) WorkFlowClient {
	return &workFlowClient{cc}
}

func (c *workFlowClient) PendingRecords(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Records, error) {
	out := new(Records)
	err := grpc.Invoke(ctx, "/workFlowClient.WorkFlow/PendingRecords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workFlowClient) NotifyRecordsPicked(ctx context.Context, in *Records, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/workFlowClient.WorkFlow/NotifyRecordsPicked", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workFlowClient) NotifyRecordsProcessed(ctx context.Context, in *Records, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/workFlowClient.WorkFlow/NotifyRecordsProcessed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WorkFlow service

type WorkFlowServer interface {
	PendingRecords(context.Context, *Request) (*Records, error)
	NotifyRecordsPicked(context.Context, *Records) (*Response, error)
	NotifyRecordsProcessed(context.Context, *Records) (*Response, error)
}

func RegisterWorkFlowServer(s *grpc.Server, srv WorkFlowServer) {
	s.RegisterService(&_WorkFlow_serviceDesc, srv)
}

func _WorkFlow_PendingRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkFlowServer).PendingRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workFlowClient.WorkFlow/PendingRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkFlowServer).PendingRecords(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkFlow_NotifyRecordsPicked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Records)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkFlowServer).NotifyRecordsPicked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workFlowClient.WorkFlow/NotifyRecordsPicked",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkFlowServer).NotifyRecordsPicked(ctx, req.(*Records))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkFlow_NotifyRecordsProcessed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Records)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkFlowServer).NotifyRecordsProcessed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workFlowClient.WorkFlow/NotifyRecordsProcessed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkFlowServer).NotifyRecordsProcessed(ctx, req.(*Records))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkFlow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "workFlowClient.WorkFlow",
	HandlerType: (*WorkFlowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PendingRecords",
			Handler:    _WorkFlow_PendingRecords_Handler,
		},
		{
			MethodName: "NotifyRecordsPicked",
			Handler:    _WorkFlow_NotifyRecordsPicked_Handler,
		},
		{
			MethodName: "NotifyRecordsProcessed",
			Handler:    _WorkFlow_NotifyRecordsProcessed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow.proto",
}

func init() { proto.RegisterFile("workflow.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x91, 0x4d, 0x4b, 0x33, 0x31,
	0x14, 0x85, 0x3b, 0xef, 0x4b, 0x9d, 0xce, 0x15, 0xba, 0x88, 0xa8, 0xa1, 0x20, 0x0c, 0xc1, 0xc5,
	0xac, 0x46, 0xa8, 0x3b, 0x57, 0x82, 0x1f, 0xa0, 0xa0, 0x94, 0x6c, 0x5c, 0x8a, 0x4e, 0x6e, 0x4b,
	0xe8, 0x98, 0x3b, 0xe6, 0xa6, 0x0e, 0xfd, 0xcd, 0xfe, 0x09, 0x69, 0x9c, 0x59, 0xd4, 0x8f, 0x8d,
	0xcb, 0x73, 0x4e, 0xce, 0x79, 0x12, 0x02, 0xe3, 0x96, 0xfc, 0x72, 0x5e, 0x53, 0x5b, 0x36, 0x9e,
	0x02, 0x89, 0xa8, 0xaf, 0x6b, 0x6a, 0x2f, 0x6a, 0x8b, 0x2e, 0xa8, 0x73, 0x18, 0x5e, 0xb9, 0xe0,
	0xd7, 0xe2, 0x08, 0xa0, 0xf1, 0x64, 0x56, 0x55, 0x78, 0xb4, 0x46, 0x26, 0x79, 0x52, 0x0c, 0x75,
	0xd6, 0x39, 0x37, 0x46, 0x48, 0x48, 0xdf, 0xd0, 0xb3, 0x25, 0x27, 0xff, 0xe5, 0x49, 0x91, 0xe9,
	0x5e, 0xaa, 0x33, 0x48, 0x35, 0x56, 0xe4, 0x0d, 0x8b, 0x13, 0x48, 0xd1, 0x05, 0x6f, 0x91, 0x65,
	0x92, 0xff, 0x2f, 0x76, 0xa7, 0xfb, 0xe5, 0x36, 0xae, 0x8c, 0x2c, 0xdd, 0x9f, 0x52, 0xc7, 0x30,
	0xd2, 0xc8, 0x0d, 0x39, 0xc6, 0x0d, 0xe1, 0x05, 0x99, 0x9f, 0x16, 0x18, 0xe9, 0x99, 0xee, 0xa5,
	0xca, 0x36, 0x84, 0xd7, 0x15, 0x72, 0x98, 0xbe, 0x27, 0x30, 0x7a, 0xe8, 0x26, 0xc5, 0x25, 0x8c,
	0x67, 0xe8, 0x8c, 0x75, 0x8b, 0xfe, 0x02, 0x87, 0x5f, 0x79, 0x5d, 0x6f, 0xf2, 0x43, 0x10, 0x1b,
	0x6a, 0x20, 0x6e, 0x61, 0xef, 0x9e, 0x82, 0x9d, 0xaf, 0x3b, 0x6b, 0x66, 0xab, 0x25, 0x1a, 0xf1,
	0x5b, 0x63, 0x22, 0xbf, 0x07, 0x9f, 0x2f, 0x50, 0x03, 0x71, 0x07, 0x07, 0xdb, 0x5b, 0x9e, 0x2a,
	0x64, 0xfe, 0xe3, 0xdc, 0xf3, 0x4e, 0xfc, 0xb3, 0xd3, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e,
	0x31, 0x08, 0x5f, 0xc5, 0x01, 0x00, 0x00,
}
